---
title: "clean data"
editor_options: 
  chunk_output_type: inline
header-includes:
    - \usepackage{setspace}\doublespacing
    - \usepackage{booktabs} 
    - \usepackage{tabularx}
    - \usepackage{tidy}
output:   
  bookdown::pdf_document2:
  fig_caption: true
  fontsize: 10.5pt
---
henter pakker
```{r hente-pakker, message=FALSE, include=FALSE, echo=FALSE}
library(dplyr) # Kan rense det nye data
library(tidyr)
library(stringr) # Til arbejde med string-data
library(ggplot2) # Til visualisering af resultater
library(viridis)
library(lubridate)
library(ggpubr) # Flere plots sammen
library(openxlsx) # Kan loade og gemme excel
library(ggpubr)
library(tidyverse)
library(haven) # til at åbne datasæt 
```

#åbne data
```{r åbne data, include=FALSE, echo=FALSE}
ESS18 <- read_dta("../original data/ESS9e02.dta")
#.. betyder gå tilabe til parent folder
```

```{r - remove all nans, include=FALSE, echo=FALSE}

not_all_na <- function(x) {!all(is.na(x))} #funktion, som angive at slette variabler hvor alle observation er NA
not_all_zero <- function(x) {!all(x == 0)} #funktion, som angive at slette variabler hvor alle observation er nul
ESS18 <- ESS18 %>%
  select_if(not_all_na) %>%
  select_if(not_all_zero)

```


med datasættet følger en ID variable (idno), tjekker at igen går igen
```{r}
ESS18_id <- ESS18 %>%
  group_by(idno)%>%
  summarise(n = n())%>%
  ungroup()
table(ESS18_id$n)
```

da en 1/3 af dataen ikke har en unik id variable, laver jeg en - id. 
```{r}
ESS18 <- mutate(ESS18, id = rownames(ESS18))
```


```{r}
write.csv(ESS18, file = ("../original data/ESS18.csv"))
```


laver seperate datasæt for de forskellige teamer, så jeg bedre kan overskue dem, gemmer idno i dem alle. 
så er det nemmere at gennemskue. 
```{r subset dataset, include=FALSE, echo=FALSE}
ESS18_media_social_trust <- subset(ESS18, select = c(id, nwspol:pplhlp))
ESS18_politics <- subset(ESS18, select = c(id, polintr:imwbcnt))
ESS18_wellbeing <- subset(ESS18, select = c(id, happy:vteubcmb))
ESS18_timing <- subset(ESS18, select = c(id, evpdemp:plnftr))
ESS18_gender <- subset(ESS18, select = c(id, hhmmb:rshipa15))
ESS18_sociademo <- subset(ESS18, select = c(id, rshpsts:regunit))
ESS18_justice <- subset(ESS18, select = c(id, frprtpl:pcmpinj))
ESS18_values <- subset(ESS18, select = c(id, ipcrtiv:impfun))
ESS18_admin <- subset(ESS18, select = -c(nwspol:pplhlp, polintr:imwbcnt, happy:vteubcmb, evpdemp:plnftr, hhmmb:rshipa15, rshpsts:regunit, frprtpl:pcmpinj, ipcrtiv:impfun))


```


```{r}
write.csv(ESS18_media_social_trust, file = ("../tema datasæt/ESS18_media_social_trust.csv"))
write.csv(ESS18_politics, file = ("../tema datasæt/ESS18_politics.csv"))
write.csv(ESS18_wellbeing, file = ("../tema datasæt/ESS18_wellbeing.csv"))
write.csv(ESS18_timing, file = ("../tema datasæt/ESS18_timing.csv"))
write.csv(ESS18_gender, file = ("../tema datasæt/ESS18_gender.csv"))
write.csv(ESS18_sociademo, file = ("../tema datasæt/ESS18_sociademo.csv"))
write.csv(ESS18_justice, file = ("../tema datasæt/ESS18_justice.csv"))
write.csv(ESS18_values, file = ("../tema datasæt/ESS18_values.csv"))
write.csv(ESS18_admin, file = ("../tema datasæt/ESS18_admin.csv"))
```


```{r - slut}
rm(list=ls())
```


